/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        'headline': ['system-ui', '-apple-system', 'sans-serif'],
        'body': ['system-ui', '-apple-system', 'sans-serif'],
        'label': ['system-ui', '-apple-system', 'sans-serif'],
      },
      colors: {
        'on-background': '#1a1c1c',
        'primary-fixed': '#b7f0bd',
        'on-surface-variant': '#414941',
        'on-tertiary-fixed': '#400107',
        'secondary-container': '#e4e2e1',
        'tertiary-fixed': '#ffdad8',
        'on-secondary-container': '#656464',
        'error-container': '#ffdad6',
        'surface-container-low': '#f3f3f3',
        'on-primary-container': '#f7fff3',
        'surface-container': '#eeeeee',
        'secondary-fixed-dim': '#c8c6c5',
        'secondary-fixed': '#e4e2e1',
        'error': '#ba1a1a',
        'inverse-surface': '#2f3131',
        'outline': '#717970',
        'on-error': '#ffffff',
        'surface-bright': '#f9f9f9',
        'primary-container': '#4c8056',
        'on-primary-fixed': '#00210a',
        'background': '#f9f9f9',
        'surface-tint': '#356941',
        'surface': '#f9f9f9',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e2e2e2',
        'on-secondary': '#ffffff',
        'on-primary-fixed-variant': '#1c512b',
        'outline-variant': '#c1c9be',
        'on-surface': '#1a1c1c',
        'surface-dim': '#dadada',
        'on-tertiary': '#ffffff',
        'on-primary': '#ffffff',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'tertiary': '#964141',
        'on-secondary-fixed': '#1b1c1c',
        'primary': '#33673f',
        'on-tertiary-fixed-variant': '#7b2c2e',
        'primary-fixed-dim': '#9cd4a3',
        'tertiary-container': '#b55958',
        'inverse-primary': '#9cd4a3',
        'tertiary-fixed-dim': '#ffb3b1',
        'on-secondary-fixed-variant': '#474747',
        'on-tertiary-container': '#fffbff',
        'on-error-container': '#93000a',
        'secondary': '#5f5e5e',
        'inverse-on-surface': '#f1f1f1',
      },
      borderRadius: {
        'none': '0px',
        'sm': '0px',
        'DEFAULT': '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        '3xl': '0px',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
