import { DailyQuote } from './types';

export const QUOTES: DailyQuote[] = [
  {"chinese":"千万别在这上面押宝", "english":"Don't bet on it"},
  {"chinese":"采取一个大胆的态度", "english":"Adopt an adventurous attitude"},
  {"chinese":"听取专家的意见", "english":"Follow the advice of experts"},
  {"chinese":"你会发现你自己无法妥协", "english":"You could find yourself unable to compromise"},
  {"chinese":"专注在你的家庭生活上吧", "english":"Focus on your home life"},
  {"chinese":"研究，然后享受它", "english":"Investigate and then enjoy it"},
  {"chinese":"当然", "english":"Definitely"},
  {"chinese":"它仍将无法预测", "english":"It will remain unpredictable"},
  {"chinese":"绝对不", "english":"Absolutely not"},
  {"chinese":"带着好玩的好奇心去探索它", "english":"Explore it with playful curiosity"},
  {"chinese":"最好等等看", "english":"Better to wait"},
  {"chinese":"它好像是确定的", "english":"It seems assured"},
  {"chinese":"趁早做", "english":"Do it early"},
  {"chinese":"对别人保密", "english":"Keep it to yourself"},
  {"chinese":"可能会发生一些令人吃惊的事作为结局", "english":"Startling events may occur as result"},
  {"chinese":"答案可能会是以另一种语言形式来到你身边", "english":"The answer may come to you in another language"},
  {"chinese":"你将需要适当调整一下", "english":"You will need to accommodate"},
  {"chinese":"怀疑它", "english":"Doubt it"},
  {"chinese":"它将会带来好运", "english":"It will bring good luck"},
  {"chinese":"要有耐心点", "english":"Be patient"},
  {"chinese":"你会发现你所需要知道的一切", "english":"You will find out everything you'll need to know"},
  {"chinese":"有一个实质性的连接链接到另种情况", "english":"There is a substantial link to another situation"},
  {"chinese":"你将会很开心你这样做了", "english":"You'll be happy you did"},
  {"chinese":"把它写下来", "english":"Get it in writing"},
  {"chinese":"千万别陷入你的个人感情", "english":"Don't get caught up in your emotions"},
  {"chinese":"改变你的焦点", "english":"Shift your focus"},
  {"chinese":"这时候非常不顺利", "english":"Unfavorable at this time"},
  {"chinese":"用任何你能做到的方式去提升", "english":"Upgrade any way you can"},
  {"chinese":"如果你照你说的做", "english":"If you do as you're told"},
  {"chinese":"如果它是做的很好的；如果不是，就再也不要做它了", "english":"If it's done well;if not,don't do it at all"},
  {"chinese":"这个时候不要要求更多", "english":"Don't ask for any more at this time"},
  {"chinese":"避开第一个解决方案", "english":"Avoid the first solution"},
  {"chinese":"观察，看看会发生什么事", "english":"Watch and see what happens"},
  {"chinese":"它会影响到其他人怎么看你", "english":"It will affect how others see you"},
  {"chinese":"你会得到最终决定", "english":"You'll get the final word"},
  {"chinese":"以一个更加轻松的速度行进吧", "english":"Proceed at a more relaxed pace"},
  {"chinese":"最好的解决方法可能不是显而易见的那个", "english":"The best solution may not be the obvious one"},
  {"chinese":"保持灵活性", "english":"Remain flexible"},
  {"chinese":"这不是你所能控制的", "english":"That's out of your control"},
  {"chinese":"只要你说“谢谢”", "english":"Provided you say 'Thank you'"},
  {"chinese":"享受体验", "english":"Enjoy the experience"},
  {"chinese":"谨慎地处理", "english":"Approach cautiously"},
  {"chinese":"注意细节", "english":"Pay attention to the details"},
  {"chinese":"当你要去做的时候，小心行事", "english":"Watch your step as you go"},
  {"chinese":"毫无保留地把它说出来", "english":"Speak up about it"},
  {"chinese":"不要犹豫了", "english":"Don't hesitate"},
  {"chinese":"它有着非常重要的意义", "english":"It is significant"},
  {"chinese":"更换一下重要事项的优先顺序", "english":"Reprioritize what is important"},
  {"chinese":"这是一个做一个新计划的最好时机了", "english":"This is a good time to make a new plan"},
  {"chinese":"继续前进", "english":"Move on"},
  {"chinese":"做个为什么不这样的清单", "english":"Make a list of why not"},
  {"chinese":"不要等待", "english":"Don't wait"},
  {"chinese":"它将是你无法忘怀的事", "english":"It is something you won't forget"},
  {"chinese":"期望能够解决", "english":"Expect to settle"},
  {"chinese":"找出更多的选择", "english":"Seek out more options"},
  {"chinese":"履行你自己的义务", "english":"Follow through on your obligations"},
  {"chinese":"稍后处理它", "english":"Deal with it later"},
  {"chinese":"跟随其他人的指引", "english":"Follow someone else's lead"},
  {"chinese":"做一个为什么的清单", "english":"Make a list of why"},
  {"chinese":"冒险一试", "english":"Take a chance"},
  {"chinese":"接受你习惯的改变", "english":"Accept a change to your routine"},
  {"chinese":"你需要采取主动", "english":"You'll need to take the initiative"},
  {"chinese":"这可保证不了", "english":"There is no guarantee"},
  {"chinese":"情况将会转变地非常快", "english":"The circumstances will change very quickly"},
  {"chinese":"你将不得不妥协", "english":"You'll have to compromise"},
  {"chinese":"你需要更多的信息", "english":"You'll need more information"},
  {"chinese":"相信你最初的想法", "english":"Trust your original thought"},
  {"chinese":"它将引起一场轰动", "english":"It will create a stir"},
  {"chinese":"可能会发生一些令人吃惊的事作为结局", "english":"Startling events may occur as result"},
  {"chinese":"它将会带来好运", "english":"It will bring good luck"},
  {"chinese":"如果它是做的很好的；如果不是，就再也不要做它了", "english":"If it's done well;if not,don't do it at all"},
  {"chinese":"这个时候不要要求更多", "english":"Don't ask for any more at this time"},
  {"chinese":"意识到太多的选择难如太少", "english":"Realize that too many choices is as too few"},
  {"chinese":"是的", "english":"Yes"},
  {"chinese":"更加仔细地聆听，然后你将会知道", "english":"Listen more carefully then you will know"},
  {"chinese":"答案就在你身边", "english":"The answer is in your backyard"},
  {"chinese":"让它过去吧", "english":"Let it go"},
  {"chinese":"那将会是一种金钱的浪费", "english":"That would be a waste of money"},
  {"chinese":"全力以赴", "english":"Give it all you've got"},
  {"chinese":"你不要真的在意", "english":"You don't really care"},
  {"chinese":"你需要考虑考虑其他方式", "english":"You'll need to consider other ways"},
  {"chinese":"从现在起的一年都没有什么所谓", "english":"A year from now it won't matter"},
  {"chinese":"不要浪费你的时间了", "english":"Don't waste your time"},
  {"chinese":"它可能是非凡的", "english":"It could be extraordinary"},
  {"chinese":"数到10，再问一次", "english":"Count to 10;ask again"},
  {"chinese":"装作它已经是真的了", "english":"Act as thought it is already real"},
  {"chinese":"布置优先次序将会是过程中一个必需的部分", "english":"Setting priorities will be a necessary part of the process"},
  {"chinese":"运用你的想象", "english":"Use your imagination"},
  {"chinese":"它一定会很好", "english":"It's gonna be great"},
  {"chinese":"确保最好的决定，镇定下来", "english":"To ensure the best decision, be calm"},
  {"chinese":"等待", "english":"Wait"},
  {"chinese":"当你行动的时候，你将需要不断弥补", "english":"You'll have to make it up as you go"},
  {"chinese":"一笑置之", "english":"Laugh about it"},
  {"chinese":"别人也同样取决于你的选择", "english":"Others will depend on your choices"},
  {"chinese":"你将会后悔的", "english":"You'll regret it"},
  {"chinese":"无可非议", "english":"Unquestionably"},
  {"chinese":"当然", "english":"Of course"},
  {"chinese":"你知道现在比之前更好了", "english":"You know better now than ever before"},
  {"chinese":"相信你的直觉", "english":"Trust your intuition"},
  {"chinese":"把它看作一个机会", "english":"Consider it an opportunity"},
  {"chinese":"问问你的母亲", "english":"Ask your mother"},
  {"chinese":"可能，当你老的时候", "english":"Perhaps, when you're older"},
  {"chinese":"只能做一次", "english":"Only do it once"},
  {"chinese":"可能", "english":"Maybe"},
  {"chinese":"千万别在这上面押宝", "english":"Don't bet on it"},
  {"chinese":"采取一个大胆的态度", "english":"Adopt an adventurous attitude"},
  {"chinese":"不行", "english":"No"},
  {"chinese":"行", "english":"Yes"},
  {"chinese":"你的行动将会改善一切", "english":"Your actions will improve things"},
  {"chinese":"别傻了", "english":"Don't be ridiculous"},
  {"chinese":"千万别在这上面押宝", "english":"Don't bet on it"},
  {"chinese":"采取一个大胆的态度", "english":"Adopt an adventurous attitude"},
  {"chinese":"听取专家的意见", "english":"Follow the advice of experts"},
  {"chinese":"你会发现你自己无法妥协", "english":"You could find yourself unable to compromise"},
  {"chinese":"专注在你的家庭生活上吧", "english":"Focus on your home life"},
  {"chinese":"研究，然后享受它", "english":"Investigate and then enjoy it"},
  {"chinese":"当然", "english":"Definitely"},
  {"chinese":"它仍将无法预测", "english":"It will remain unpredictable"},
  {"chinese":"绝对不", "english":"Absolutely not"},
  {"chinese":"带着好玩的好奇心去探索它", "english":"Explore it with playful curiosity"},
  {"chinese":"欣然地确定它", "english":"Be delightfully sure of it"},
  {"chinese":"最好等等看", "english":"Better to wait"},
  {"chinese":"对别人保密", "english":"Keep it to yourself"},
  {"chinese":"可能会发生一些令人吃惊的事作为结局", "english":"Startling events may occur as result"},
  {"chinese":"问问你的父亲", "english":"Ask your father"},
  {"chinese":"绝不", "english":"Never"},
  {"chinese":"答案可能会是以另一种语言形式来到你身边", "english":"The answer may come to you in another language"},
  {"chinese":"你将需要适当调整一下", "english":"You will need to accommodate"},
  {"chinese":"怀疑它", "english":"Doubt it"},
  {"chinese":"它将会带来好运", "english":"It will bring good luck"},
  {"chinese":"要有耐心点", "english":"Be patient"},
  {"chinese":"你会发现你所需要知道的一切", "english":"You will find out everything you'll need to know"},
  {"chinese":"有一个实质性的连接链接到另种情况", "english":"There is a substantial link to another situation"},
  {"chinese":"观察，看看会发生什么事", "english":"Watch and see what happens"},
  {"chinese":"它会影响到其他人怎么看你", "english":"It will affect how others see you"},
  {"chinese":"你将会很开心你这样做了", "english":"You'll be happy you did"},
  {"chinese":"把它写下来", "english":"Get it in writing"},
  {"chinese":"这时候非常不顺利", "english":"Unfavorable at this time"},
  {"chinese":"用任何你能做到的方式去提升", "english":"Upgrade any way you can"},
  {"chinese":"如果你照你说的做", "english":"If you do as you're told"},
  {"chinese":"移除你自己的阻碍", "english":"Remove your own obstacles"},
  {"chinese":"最好把注意力放在你的工作上", "english":"It would be better to focus on your work"},
  {"chinese":"赌一下", "english":"Bet on it"},
  {"chinese":"先把其他事完成", "english":"Finish something else first"},
  {"chinese":"你可能有敌对的人", "english":"You may have opposition"},
  {"chinese":"你太靠近看了", "english":"You are too close to see"},
  {"chinese":"情况还不清楚", "english":"The situation is unclear"},
  {"chinese":"需要一个实质性的努力", "english":"A substantial effort will be required"},
  {"chinese":"先让你自己休息一下", "english":"Allow yourself to rest first"},
  {"chinese":"这个机会不会很快再来", "english":"The chance will not come again soon"},
  {"chinese":"再重新考虑你的方法", "english":"Reconsider your approach"},
  {"chinese":"它将是不可取的", "english":"It would be inadvisable"},
  {"chinese":"等待一个更好的提议", "english":"Wait for a better offer"},
  {"chinese":"早点定下来", "english":"Settle it soon"},
  {"chinese":"是的，但是别强迫", "english":"Yes, but don't force it"},
  {"chinese":"去取得一个更加清晰的视野", "english":"Get a clearer view"},
  {"chinese":"实际点", "english":"Be practical"},
  {"chinese":"节省你的能量吧", "english":"Save your energy"},
  {"chinese":"冒险一试", "english":"Take a chance"},
  {"chinese":"现在你可以", "english":"Now you can"},
  {"chinese":"不要做得过火了", "english":"Don't overdo it"},
  {"chinese":"它将会扶持你", "english":"It will sustain you"},
  {"chinese":"你将为它付出代价", "english":"It'll cost you"},
  {"chinese":"它肯定会把事情变得有趣", "english":"It is sure to make things interesting"},
  {"chinese":"结果会是积极的", "english":"The outcome will be positive"},
  {"chinese":"无论如何", "english":"No matter what"},
  {"chinese":"它是肯定的", "english":"It is certain"},
  {"chinese":"它将是一种乐趣", "english":"It will be a pleasure"},
  {"chinese":"它是不确定的", "english":"It is uncertain"},
  {"chinese":"更加慷慨点", "english":"Be more generous"},
  {"chinese":"你可能必须要丢下其他的东西", "english":"You may have to drop other things"},
  {"chinese":"不用担心", "english":"Don't be concerned"},
  {"chinese":"对意外情况做好准备", "english":"Prepare for the unexpected"},
  {"chinese":"它没有什么意义", "english":"It is not significant"},
  {"chinese":"告诉别人它对你意味着什么", "english":"Tell someone what it means to you"},
  {"chinese":"你可能必须要丢下其他的东西", "english":"You may have to drop other things"},
  {"chinese":"无论你做什么，结果都将会持续下去", "english":"Whatever you do the results will be lasting"},
  {"chinese":"保持开放的心态", "english":"Keep an open mind"},
  {"chinese":"制作计划的好时机", "english":"It's a good time to make plans"},
  {"chinese":"它可能很难，但是你会发现它是有价值的", "english":"It may be difficult but you will find value in it"},
  {"chinese":"它值得麻烦", "english":"It is worth the trouble"},
  {"chinese":"采取一个大胆的态度", "english":"Adopt an adventurous attitude"},
  {"chinese":"听取专家的意见", "english":"Follow the advice of experts"},
  {"chinese":"将会有阻碍需要去克服", "english":"There will be obstacles to overcome"},
  {"chinese":"相关联的问题可能会浮出水面", "english":"Related issues may surface"},
  {"chinese":"你肯定需要支持", "english":"You are sure to have support"},
  {"chinese":"协助将会使你向成功发展", "english":"Assistance would make your progress a success"},
  {"chinese":"合作将会是至关重要的", "english":"Collaboration will be the key"},
  {"chinese":"接管", "english":"Take charge"},
  {"chinese":"不能失败", "english":"It cannot fail"},
  {"chinese":"温和的坚持会有回报的", "english":"Gentle persistence will pay off"},
  {"chinese":"你将不会失望", "english":"You will not be disappointed"},
  {"chinese":"找出更多的提议", "english":"Seek out more options"},
  {"chinese":"它可能是一个木已成舟的事", "english":"It may already be a done deal"},
  {"chinese":"贯彻你的良好心愿", "english":"Follow through with your good intentions"},
  {"chinese":"花多点时间去决定", "english":"Take more time to decide"},
  {"chinese":"不要被迫太快行动", "english":"Don't be pressured into acting too quickly"},
  {"chinese":"不要忽略那些显而易见的事", "english":"Don't ignore the obvious"},
  {"chinese":"你必须现在行动", "english":"You must act now"},
  {"chinese":"它不值得努力", "english":"It's not worth a struggle"},
  {"chinese":"如果你不抵抗", "english":"If you don't resist"},
  {"chinese":"遵守规则", "english":"Respect the rules"},
  {"chinese":"别忘记了享受乐趣", "english":"Don't forget to have fun"},
  {"chinese":"不要怀疑", "english":"Don't doubt it"},
  {"chinese":"一个有力的承诺将会获得好的结果", "english":"A strong commitment will achieve good results"},
  {"chinese":"试试一个不太可能的解决方案", "english":"Try a more unlikely solution"},
  {"chinese":"放弃老的解决方案", "english":"Leave behind old solutions"},
  {"chinese":"不，如果你独自一个人的话", "english":"Not if you're alone"},
  {"chinese":"灾难是极有可能的", "english":"Mishaps are highly probable"},
  {"chinese":"迫切要求终止", "english":"Press for closure"},
  {"chinese":"听取专家的意见", "english":"Follow the advice of experts"},
  {"chinese":"你会发现你自己无法妥协", "english":"You could find yourself unable to compromise"},
  {"chinese":"专注在你的家庭生活上吧", "english":"Focus on your home life"},
  {"chinese":"研究，然后享受它", "english":"Investigate and then enjoy it"},
  {"chinese":"当然", "english":"Definitely"},
  {"chinese":"它仍将无法预测", "english":"It will remain unpredictable"},
  {"chinese":"绝对不", "english":"Absolutely not"},
  {"chinese":"带着好玩的好奇心去探索它", "english":"Explore it with playful curiosity"},
  {"chinese":"最好等等看", "english":"Better to wait"},
  {"chinese":"它好像是确定的", "english":"It seems assured"},
  {"chinese":"趁早做", "english":"Do it early"},
  {"chinese":"对别人保密", "english":"Keep it to yourself"},
  {"chinese":"可能会发生一些令人吃惊的事作为结局", "english":"Startling events may occur as result"},
  {"chinese":"答案可能会是以另一种语言形式来到你身边", "english":"The answer may come to you in another language"},
  {"chinese":"你将需要适当调整一下", "english":"You will need to accommodate"},
  {"chinese":"怀疑它", "english":"Doubt it"},
  {"chinese":"它将会带来好运", "english":"It will bring good luck"},
  {"chinese":"要有耐心点", "english":"Be patient"},
  {"chinese":"你会发现你所需要知道的一切", "english":"You will find out everything you'll need to know"},
  {"chinese":"有一个实质性的连接链接到另种情况", "english":"There is a substantial link to another situation"},
  {"chinese":"你将会很开心你这样做了", "english":"You'll be happy you did"},
  {"chinese":"把它写下来", "english":"Get it in writing"},
  {"chinese":"千万别陷入你的个人感情", "english":"Don't get caught up in your emotions"},
  {"chinese":"改变你的焦点", "english":"Shift your focus"},
  {"chinese":"这时候非常不顺利", "english":"Unfavorable at this time"},
  {"chinese":"用任何你能做到的方式去提升", "english":"Upgrade any way you can"},
  {"chinese":"如果你照你说的做", "english":"If you do as you're told"},
  {"chinese":"如果它是做的很好的；如果不是，就再也不要做它了", "english":"If it's done well;if not,don't do it at all"},
  {"chinese":"这个时候不要要求更多", "english":"Don't ask for any more at this time"},
  {"chinese":"避开第一个解决方案", "english":"Avoid the first solution"},
  {"chinese":"观察，看看会发生什么事", "english":"Watch and see what happens"},
  {"chinese":"它会影响到其他人怎么看你", "english":"It will affect how others see you"},
  {"chinese":"你会得到最终决定", "english":"You'll get the final word"},
  {"chinese":"以一个更加轻松的速度行进吧", "english":"Proceed at a more relaxed pace"},
  {"chinese":"最好的解决方法可能不是显而易见的那个", "english":"The best solution may not be the obvious one"},
  {"chinese":"保持灵活性", "english":"Remain flexible"},
  {"chinese":"这不是你所能控制的", "english":"That's out of your control"},
  {"chinese":"只要你说“谢谢”", "english":"Provided you say 'Thank you'"},
  {"chinese":"享受体验", "english":"Enjoy the experience"},
  {"chinese":"谨慎地处理", "english":"Approach cautiously"},
  {"chinese":"注意细节", "english":"Pay attention to the details"},
  {"chinese":"当你要去做的时候，小心行事", "english":"Watch your step as you go"},
  {"chinese":"毫无保留地把它说出来", "english":"Speak up about it"},
  {"chinese":"不要犹豫了", "english":"Don't hesitate"},
  {"chinese":"它有着非常重要的意义", "english":"It is significant"},
  {"chinese":"更换一下重要事项的优先顺序", "english":"Reprioritize what is important"},
  {"chinese":"这是一个做一个新计划的最好时机了", "english":"This is a good time to make a new plan"},
  {"chinese":"继续前进", "english":"Move on"},
  {"chinese":"做个为什么不这样的清单", "english":"Make a list of why not"},
  {"chinese":"不要等待", "english":"Don't wait"},
  {"chinese":"它将是你无法忘怀的事", "english":"It is something you won't forget"},
  {"chinese":"期望能够解决", "english":"Expect to settle"},
  {"chinese":"找出更多的选择", "english":"Seek out more options"},
  {"chinese":"履行你自己的义务", "english":"Follow through on your obligations"},
  {"chinese":"稍后处理它", "english":"Deal with it later"},
  {"chinese":"跟随其他人的指引", "english":"Follow someone else's lead"},
  {"chinese":"做一个为什么的清单", "english":"Make a list of why"},
  {"chinese":"冒险一试", "english":"Take a chance"},
];

export const NUMBER_WORDS: Record<number, string> = {
  1: "one",
  2: "two",
  3: "three",
  4: "four",
  5: "five",
  6: "six",
  7: "seven",
  8: "eight",
  9: "nine",
  10: "ten",
  11: "eleven",
  12: "twelve",
  13: "thirteen",
  14: "fourteen",
  15: "fifteen",
  16: "sixteen",
  17: "seventeen",
  18: "eighteen",
  19: "nineteen",
  20: "twenty",
  21: "twenty-one",
  22: "twenty-two",
  23: "twenty-three",
  24: "twenty-four",
  25: "twenty-five",
  26: "twenty-six",
  27: "twenty-seven",
  28: "twenty-eight",
  29: "twenty-nine",
  30: "thirty",
  31: "thirty-one"
};

export const MONTH_NAMES_CN = [
  "一月", "二月", "三月", "四月", "五月", "六月",
  "七月", "八月", "九月", "十月", "十一月", "十二月"
];

export const WEEKDAYS_CN = [
  "星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"
];
